default:
  dlq: "./data/error_dlq.log"
  registry: "./.logging_registry"
  output: "./logs/output.log"
  inputs: ["./logs/*.log"]
server:
    enabled: true
    port: 8080
pipeline:
  stripper:
    - { field: "user" }
    - { field: "id" }
  filter:
    # - { field: "level", value: "DEBUG" }
  masker:
    - { field: "card", preset: "card" }
    - { field: "password", range: "full" }
    - { field: "email", preset: "email" }
