default:
  inputs: 
    - "./data/*.log"
  output: "./data/output.log"
  registry: "./.logging_registry"

pipeline:
  stripper:
    - { field: "user" }
    - { field: "id" }
  filter:
    - { field: "level", value: "DEBUG" }
  masker:
    - { field: "card", preset: "card" }
    - { field: "password", range: "full" }
    - { field: "email", preset: "email" }
